spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail}
    password: ${passwd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true